apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: llama-validator
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  path: ./flux/apps/validator
  sourceRef:
    kind: GitRepository
    name: llama-training-source
  targetNamespace: soperator
